# Import

In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import uniform
from scipy.stats import bootstrap
from copy import deepcopy

In [2]:
mine_prop = gpd.read_file('data\mine-comm\snl_mining_properties.gpkg')
snl_prod = pd.read_csv('data\mine-comm\snl_production_values.csv')

In [3]:
mine_prop.head()

,mine,snl_id,known_as,primary_commodity,list_of_commodities,development_stage,operating_status,mine_type_1,mine_type_2,mine_type_3,country,coordinate_accuracy,geometry
0,101,64665,None,Coal,Coal,Operating,None,None,None,None,Brazil,Exact,POINT (-49.24552 -28.73240)
1,1068,79522,None,Gold,"Gold,Copper,Molybdenum",Exploration,Active,None,None,None,Mexico,Best Guess,POINT (-109.32652 29.06976)
2,11 RAU-Novaya,68289,None,Coal,Coal,Grassroots,Inactive,None,None,None,Ukraine,Best Guess,POINT (38.65827 48.51954)
3,1165L,63154,None,Coal,Coal,Advanced Exploration,Inactive,Open Pit,None,None,Mozambique,Exact,POINT (34.00000 -16.23000)
4,119 Property,32960,"866119/00, Aripuana 3 Cluster, ARP-03 Cluster,...",Diamonds,Diamonds,Exploration,Inactive,Placer,None,None,Brazil,Exact,POINT (-58.83353 -11.48279)

In [9]:
mine_prop.development_stage.value_counts()

development_stage
Exploration             7464
Operating               5396
Grassroots              5134
Target Outline          4648
Reserves Development    4005
Closed                  1634
Advanced Exploration    1112
Prefeas/Scoping          913
Feasibility              677
Satellite                535
Expansion                313
Preproduction            281
Limited Production       233
Feasibility Complete     204
Feasibility Started      200
Construction Started     178
Construction Planned      94
Commissioning             31
Residual Production       26
Name: count, dtype: int64

Well we have to assess what development stages have what production volume.

Filter for year 2017 as it is the year where also the indigenous territory data was aquired

In [12]:
snl_prod.head()
snl_prod17 = snl_prod[snl_prod.year == 2017]

In [13]:
snl_prod17.shape

(1319975, 5)

In [14]:
snl_prod17.columns

Index(['snl_id', 'commodity', 'year', 'value', 'unit'], dtype='object')

In [22]:
snl_prod17[~snl_prod17.isna()].count() / snl_prod.shape[0] *100

snl_id       24.503311
commodity    24.503311
year         24.503311
value         0.062540
unit         24.503311
dtype: float64

In [27]:
snl_prod17.count() / snl_prod.shape[0] *100

snl_id       24.503311
commodity    24.503311
year         24.503311
value         0.062540
unit         24.503311
dtype: float64

In [26]:
snl_prod17[snl_prod17.year.isna()].head()

Empty DataFrame
Columns: [snl_id, commodity, year, value, unit]
Index: []